# Generated by Django 3.0.2 on 2020-01-21 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='table_co',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_city', models.CharField(max_length=64)),
                ('_location', models.CharField(max_length=64)),
                ('_value', models.CharField(max_length=64)),
                ('_date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='table_h2s',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_city', models.CharField(max_length=64)),
                ('_location', models.CharField(max_length=64)),
                ('_value', models.CharField(max_length=64)),
                ('_date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='table_no',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_city', models.CharField(max_length=64)),
                ('_location', models.CharField(max_length=64)),
                ('_value', models.CharField(max_length=64)),
                ('_date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='table_no2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_city', models.CharField(max_length=64)),
                ('_location', models.CharField(max_length=64)),
                ('_value', models.CharField(max_length=64)),
                ('_date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='table_nox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_city', models.CharField(max_length=64)),
                ('_location', models.CharField(max_length=64)),
                ('_value', models.CharField(max_length=64)),
                ('_date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='table_o3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_city', models.CharField(max_length=64)),
                ('_location', models.CharField(max_length=64)),
                ('_value', models.CharField(max_length=64)),
                ('_date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='table_pm10',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_city', models.CharField(max_length=64)),
                ('_location', models.CharField(max_length=64)),
                ('_value', models.CharField(max_length=64)),
                ('_date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='table_pm25',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_city', models.CharField(max_length=64)),
                ('_location', models.CharField(max_length=64)),
                ('_value', models.CharField(max_length=64)),
                ('_date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='table_so2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_city', models.CharField(max_length=64)),
                ('_location', models.CharField(max_length=64)),
                ('_value', models.CharField(max_length=64)),
                ('_date', models.DateField(auto_now=True)),
            ],
        ),
    ]
