# Generated by Django 3.0.2 on 2020-01-21 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_my_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table_co',
            name='_value',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='table_h2s',
            name='_value',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='table_no',
            name='_value',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='table_no2',
            name='_value',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='table_nox',
            name='_value',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='table_o3',
            name='_value',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='table_pm10',
            name='_value',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='table_pm25',
            name='_value',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='table_so2',
            name='_value',
            field=models.IntegerField(),
        ),
    ]
