# Generated by Django 3.0.2 on 2020-01-21 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_my_app', '0002_auto_20200121_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table_co',
            name='_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='table_h2s',
            name='_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='table_no',
            name='_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='table_no2',
            name='_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='table_nox',
            name='_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='table_o3',
            name='_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='table_pm10',
            name='_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='table_pm25',
            name='_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='table_so2',
            name='_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
