# Generated by Django 2.2.1 on 2019-05-18 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tehnicka', '0002_auto_20190514_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='predmet',
            name='razred',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
