# Generated by Django 2.2.1 on 2019-05-19 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tehnicka', '0003_predmet_razred'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diploma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razred_id', models.IntegerField()),
                ('razred_naziv', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name_plural': 'Diplome',
            },
        ),
        migrations.RenameField(
            model_name='predmet',
            old_name='razred',
            new_name='ocjena',
        ),
        migrations.DeleteModel(
            name='Ocjena',
        ),
        migrations.AddField(
            model_name='diploma',
            name='predmeti',
            field=models.ManyToManyField(to='tehnicka.Predmet'),
        ),
    ]
