# Generated by Django 2.2.1 on 2019-05-28 22:32

from django.db import migrations, models
import tehnicka.models


class Migration(migrations.Migration):

    dependencies = [
        ('tehnicka', '0004_remove_ucenik_jmbg'),
    ]

    operations = [
        migrations.AddField(
            model_name='ucenik',
            name='godina_upisa',
            field=models.IntegerField(default=tehnicka.models.current_year),
        ),
    ]
