# Generated by Django 2.2.1 on 2019-05-19 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tehnicka', '0005_ucenik_diploma_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predmet',
            name='ocjena',
            field=models.IntegerField(null=True),
        ),
    ]
