# Generated by Django 2.2.1 on 2019-05-19 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tehnicka', '0006_auto_20190519_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='diploma',
            name='ucenik_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
