# Generated by Django 2.2.1 on 2019-05-19 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tehnicka', '0007_diploma_ucenik_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diploma',
            name='ucenik_id',
            field=models.IntegerField(default='0'),
        ),
    ]
