# Generated by Django 2.2.1 on 2019-05-20 04:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tehnicka', '0008_auto_20190519_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ucenik',
            name='diploma_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='tehnicka.Diploma'),
        ),
    ]
