# Generated by Django 2.2.1 on 2019-05-20 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tehnicka', '0009_auto_20190520_0406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ucenik',
            name='diploma_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tehnicka.Diploma'),
        ),
    ]
