# Generated by Django 2.2.1 on 2019-05-20 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tehnicka', '0010_auto_20190520_1030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ucenik',
            name='diploma_id',
        ),
    ]
