# Generated by Django 2.2.1 on 2019-05-20 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tehnicka', '0011_remove_ucenik_diploma_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predmet',
            name='ocjena',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
