# Generated by Django 2.2.1 on 2019-05-21 01:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tehnicka', '0012_auto_20190520_1246'),
    ]

    operations = [
        migrations.CreateModel(
            name='Priznanja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=64)),
                ('ucenik_id', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='ucenik',
            name='priznanje_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tehnicka.Priznanja'),
        ),
    ]
