# Generated by Django 2.2.1 on 2019-05-21 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tehnicka', '0013_auto_20190521_0143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ucenik',
            name='priznanje_id',
        ),
        migrations.AddField(
            model_name='priznanja',
            name='bodovi',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='diploma',
            name='ucenik_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tehnicka.Ucenik'),
        ),
        migrations.AlterField(
            model_name='priznanja',
            name='ucenik_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tehnicka.Ucenik'),
        ),
    ]
