# Generated by Django 2.2.1 on 2019-05-28 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tehnicka', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='predmetispis',
            name='razred_id',
            field=models.IntegerField(default='5'),
        ),
    ]
