# Generated by Django 2.2.1 on 2019-05-28 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tehnicka', '0002_predmetispis_razred_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='predmetispis',
            options={'verbose_name_plural': 'Predmeti_ispis'},
        ),
    ]
