# Generated by Django 2.2.1 on 2019-05-28 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tehnicka', '0003_auto_20190528_0222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ucenik',
            name='JMBG',
        ),
    ]
